### ISSUE TITLE
Unused variable $ratesApi in view helper

### ISSUE THREAD

**Issue by asgrim** [davidyell/CakePHP-CurrencyExchange#2]
https://github.com/davidyell/CakePHP-CurrencyExchange/blob/3.x/src/View/Helper/CurrencyHelper.php#L35

This variable `$ratesApi` looks like it is never used...?

![unused](https://cloud.githubusercontent.com/assets/496145/8451359/ae74d10c-1fda-11e5-89e0-8d1835c12aa7.png)

**Comment by davidyell** [comment]
Wow, good spot. This was refactored into the shell so that the rates were not requested from the api on every page load.
