### ISSUE TITLE
Inconsistent indentation used in view helper

### ISSUE THREAD

**Issue by asgrim** [davidyell/CakePHP-CurrencyExchange#3]
![inconsistent-indent](https://cloud.githubusercontent.com/assets/496145/8451378/d14c51c8-1fda-11e5-9d44-4f9fda0e2648.png)

Sometimes tabs, sometimes spaces... not sure what the Cake rules are, but I'm sure it's not "be inconsistent" ;)

**Comment by asgrim** [comment]
Also...
![wat](https://cloud.githubusercontent.com/assets/496145/8451510/b915a2d4-1fdb-11e5-8a7c-f8342d870ee1.png)

**Comment by davidyell** [comment]
Yep, Cake 2 uses spaces and Cake 3 uses tabs. So during the upgrade process my IDE will be set to tabs. Hopefully `phpcbf` can fix these for me.
